services:
  db-backup:
    image: ghcr.io/romkey/hackstack-db-backup:${IMAGE_VERSION:-latest}
    container_name: db-backup
    hostname: db-backup
    restart: unless-stopped
    volumes:
      - ${DBBACKUP_PARENT_HOST_PATH:-/opt}:/opt
      - ${DBBACKUP_DEST_PATH}:/dest
    env_file:
      - .env
    networks:
      - db
      - mariadb

networks:
  db:
    external: true
    name: postgres-net
  mariadb:
    external: true
    name: mariadb-net
