services:
  db-backup:
    image: ghcr.io/romkey/hackstack-db-backup:latest
    hostname: db-backup
    container_name: db-backup
    restart: unless-stopped
    user: "${BACKUP_UID:-0}:${BACKUP_GID:-0}"
    env_file:
      - .env
    volumes:
      - ${DBBACKUP_PARENT_HOST_PATH}:/opt:ro
      - backup_nfs:/dest
    networks:
      - postgresql
      - mariadb

volumes:
  backup_nfs:
    driver: local
    driver_opts:
      type: nfs
      o: addr=${NFS_SERVER},${NFS_OPTIONS:-nfsvers=4,soft,rw}
      device: ":${NFS_PATH}"

networks:
  postgresql:
    external: true
    name: postgres-net
  mariadb:
    external: true
    name: mariadb-net
