services:
  dbbackup:
    image: ghcr.io/romkey/hackstack-db-backup:latest
    hostname: dbbackup
    container_name: dbbackup
    restart: unless-stopped
    volumes:
      - /opt:/opt:ro
      - backup_nfs:/dest
    networks:
      - postgresql
      - mariadb
    env_file:
      - .env

volumes:
  backup_nfs:
    driver: local
    driver_opts:
      type: nfs
      o: addr=${NFS_SERVER},${NFS_OPTIONS:-nfsvers=4,soft,rw}
      device: ":${NFS_PATH}"

networks:
  postgresql:
    external: true
    name: postgres-net
  mariadb:
    external: true
    name: mariadb-net
