services:
  statping:
    image: adamboutcher/statping-ng:${IMAGE_VERSION:-latest}
    container_name: statping
    hostname: statping
    restart: unless-stopped
    networks:
      - proxy
      - db
      - mariadb
    volumes:
      - ../../lib/statping:/app
#    ports:
#      - 8091:8080
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://127.0.0.1:8080/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 45s
networks:
  proxy:
    name: nginx-proxy-net
    external: true
  db:
    name: postgres-net
    external: true
  mariadb:
    name: mariadb-net
    external: true
