services:
  statping:
    image: adamboutcher/statping-ng:${IMAGE_VERSION:-latest}
    container_name: statping
    hostname: statping
    restart: unless-stopped
    networks:
      - proxy
      - db
      - mariadb
    volumes:
      - ../../lib/statping:/app
#    ports:
#      - 8091:8080
    env_file:
      - .env
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
networks:
  proxy:
    name: nginx-proxy-net
    external: true
  db:
    name: postgres-net
    external: true
  mariadb:
    name: mariadb-net
    external: true
