services:
  matter:
    image: ghcr.io/home-assistant-libs/python-matter-server:${IMAGE_VERSION:-stable}
    container_name: matter
    hostname: matter
    restart: unless-stopped
    security_opt:
      - apparmor=unconfined
    volumes:
      - ../../lib/matter:/data
      - /run/dbus:/run/dbus:ro
    env_file:
      - .env
    networks:
      - hass
      - mdns
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
networks:
  hass:
    name: hass-net
    external: true
  mdns:
    external: true
    name: mdns-net
