services:
  matter:
    image: ghcr.io/home-assistant-libs/python-matter-server:${IMAGE_VERSION:-stable}
    container_name: matter
    hostname: matter
    restart: unless-stopped
    security_opt:
      - apparmor=unconfined
    volumes:
      - ../../lib/matter:/data
      - /run/dbus:/run/dbus:ro
    env_file:
      - .env
    networks:
      - hass
      - mdns
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "timeout 2 bash -c '</dev/tcp/127.0.0.1/5580' || exit 1",
        ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 45s
networks:
  hass:
    name: hass-net
    external: true
  mdns:
    external: true
    name: mdns-net
