services:
  autogenerate-hosts:
    image: ghcr.io/romkey/pdxhackerspace-hackstack-autogenerate-hosts:${IMAGE_VERSION:-latest}
    container_name: autogenerate-hosts
    hostname: autogenerate-hosts
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - "${DB_PATH}:${DB_PATH}"
      - "${HOSTSFILE_PATH}:/dest"
