services:
  rtl_433:
    image: hertzg/rtl_433:${IMAGE_VERSION:-master-alpine}
    container_name: rtl_433
    hostname: rtl_433
    restart: unless-stopped
    entrypoint: "/usr/local/bin/rtl_433"
    command: "-F ${MQTT_BROKER} ${RTL433_EXTRA_OPTIONS}"
    networks:
      - mqtt
    devices:
      - "${SDR_DEVICE}"
    volumes:
      - ./config:/etc/rtl_433
    env_file:
      - .env
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
networks:
  mqtt:
    name: mosquitto-net
    external: true
