services:
  adminer:
    image: adminer:${IMAGE_VERSION:-latest}
    hostname: adminer
    container_name: adminer
    restart: unless-stopped
    networks:
      - proxy
      - db
      - mariadb
#    ports:
#      - 8080:8080
    healthcheck:
      test: ["CMD-SHELL", "curl -fSs http://127.0.0.1:8080/ >/dev/null || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 15s
networks:
  proxy:
    name: nginx-proxy-net
    external: true
  mariadb:
    name: mariadb-net
    external: true
  db:
    name: postgres-net
    external: true
