services:
  vaultwarden:
    image: vaultwarden/server:${IMAGE_VERSION:-latest-alpine}
    container_name: vaultwarden
    hostname: vaultwarden
    restart: unless-stopped
    networks:
      - proxy
      - db
    volumes:
      - ../../lib/vaultwarden:/data
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1/alive | grep -q ok || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 20s
networks:
  proxy:
    external: true
    name: nginx-proxy-net
  db:
    external: true
    name: postgres-net
