services:
  vaultwarden:
    image: vaultwarden/server:${IMAGE_VERSION:-latest-alpine}
    container_name: vaultwarden
    hostname: vaultwarden
    restart: unless-stopped
    networks:
      - proxy
      - db
    volumes:
      - ../../lib/vaultwarden:/data
    env_file:
      - .env
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
networks:
  proxy:
    external: true
    name: nginx-proxy-net
  db:
    external: true
    name: postgres-net
