services:
  jellyfin:
    image: jellyfin/jellyfin:${IMAGE_VERSION:-latest}
    container_name: jellyfin
    hostname: jellyfin
    restart: unless-stopped
    volumes:
      - ./config:/config
      - ../../log/jellyfin:/config/log
      - ../../run/jellyfin/cache:/cache
      - ../../lib/xmltv:/xmltv
      - /media/nas:/media
    ports:
#      - 8096:8096
# ? old for homerunhd
      - 8020-8030:8020-8030/udp
    env_file:
      - .env
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -fSs http://127.0.0.1:8096/health >/dev/null || exit 1",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - proxy
      - mdns
      - db
      - hass
networks:
  proxy:
    name: nginx-proxy-net
    external: true
  db:
    name: postgres-net
    external: true
  mdns:
    external: true
    name: mdns-net
  hass:
    external: true
    name: hass-net
