services:
  cups:
    build: .
    image: cups:${IMAGE_VERSION:-latest}
    container_name: cups
    hostname: cups
    restart: unless-stopped
    volumes:
      - ../../lib/cups:/config
      - ./config/cupsd.conf:/etc/cups/cupsd.conf:ro
      - ./ppds:/usr/share/cups/model/custom:ro
#   ports:
#     - 631:631
    networks:
      - cups
      - proxy
    healthcheck:
      test: ["CMD-SHELL", "curl -fSs http://localhost:631/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

networks:
  cups:
    name: cups-net
  proxy:
    external: true
    name: nginx-proxy-net
