services:
  mqtt-explorer:
    image: smeagolworms4/mqtt-explorer
    container_name: mqtt-explorer
    hostname: mqtt-explorer
    restart: unless-stopped
    networks:
      - proxy
      - mosquitto
    volumes:
      - ./config:/mqtt-explorer/config
networks:
  proxy:
    external: true
    name: nginx-proxy-net
  mosquitto:
    external: true
    name: mosquitto-net
