services:
  avahi:
    image: ydkn/avahi:${IMAGE_VERSION:-latest}
    hostname: avahi
    container_name: avahi
    restart: unless-stopped
    depends_on:
      - mdns_repeater
    volumes:
      - ./services:/etc/avahi/services
    networks:
      - mdns
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
networks:
  mdns:
    name: mdns-net
    external: true
