services:
  cyberchef:
    image: ghcr.io/gchq/cyberchef:${IMAGE_VERSION:-latest}
    container_name: cyberchef
    hostname: cyberchef
    restart: unless-stopped
    networks:
      - proxy
#    ports:
#      - 8090:80
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
networks:
  proxy:
    external: true
    name: nginx-proxy-net
