services:
  piper:
    image: rhasspy/wyoming-piper:${IMAGE_VERSION:-latest}
    container_name: piper
    hostname: piper
    restart: unless-stopped
    command: --voice en-us-lessac-low
#    ports:
#      - 10200:10200
    volumes:
      - ../../lib/piper:/data
    env_file:
      - .env
    networks:
      - hass
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
networks:
  hass:
    external: true
    name: hass-net
