services:
  piper:
    image: rhasspy/wyoming-piper:${IMAGE_VERSION:-latest}
    container_name: piper
    hostname: piper
    restart: unless-stopped
    command: --voice en-us-lessac-low
#    ports:
#      - 10200:10200
    volumes:
      - ../../lib/piper:/data
    env_file:
      - .env
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "timeout 2 bash -c '</dev/tcp/127.0.0.1/10200' || exit 1",
        ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s
    networks:
      - hass
networks:
  hass:
    external: true
    name: hass-net
