# https://hub.docker.com/r/oznu/cloudflare-ddns/
services:
  cloudflare-ddns:
    image: oznu/cloudflare-ddns:${IMAGE_VERSION:-latest}
    container_name: cloudflare-ddns
    hostname: cloudflare-ddns
    restart: unless-stopped
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pgrep -f cloudflare >/dev/null || exit 1"]
      interval: 60s
      timeout: 5s
      retries: 3
      start_period: 15s
