services:
  snapserver:
#    image: saiyato/snapserver
    image: ivdata/snapserver:${IMAGE_VERSION:-latest}
    container_name: snapserver
    hostname: snapserver
    network_mode: host
    restart: unless-stopped
#    ports:
#      - 1704:1704 # port for the actual audio streaming
#      - 1705:1705 # port for TCP Json RPC
#      - 1780:1780 # port for the SnapWeb Webinterface
    volumes:
      - ./config/snapcast.conf:/etc/snapcast.conf
      - ../../run/snapserver/fifo:/tmp/snapfile
      - ../../lib/snapserver:/var/lib/snapcast
    env_file:
      - .env
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "timeout 2 bash -c '</dev/tcp/127.0.0.1/1704' || exit 1",
        ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 15s
