services:
  auto_planka:
    image: ghcr.io/romkey/pdxhackstack-auto-planka:${IMAGE_VERSION:-latest}
    container_name: auto_planka
    hostname: auto_planka
    restart: unless-stopped
    volumes:
      - ./config:/config
    env_file:
      - .env
    networks:
      - db

networks:
  db:
    name: postgres-net
    external: true
