services:
  openwakeword:
    image: rhasspy/wyoming-openwakeword:${IMAGE_VERSION:-latest}
    container_name: openwakeword
    hostname: openwakeword
    restart: unless-stopped
    command: --preload-model 'ok_nabu' --custom-model-dir /models
    env_file:
      - .env
    volumes:
      - ../../lib/openwakeword:/models
#    ports:
#      - 10400:10400
    networks:
      - hass
    healthcheck:
      test: ["CMD-SHELL", "curl -fSs http://127.0.0.1:10400/ >/dev/null || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 20s

networks:
  hass:
    external: true
    name: hass-net
