services:
  mosquitto:
    image: eclipse-mosquitto:${IMAGE_VERSION:-latest}
    container_name: mosquitto
    hostname: mosquitto
    restart: unless-stopped
    volumes:
      - ./config:/mosquitto/config
      - ../../lib/mosquitto:/mosquitto/data
      - ../../log/mosquitto:/mosquitto/log
# ports need to be exposed in order to be available to LAN
    ports:
      - 1883:1883
    env_file:
      - .env
    # Auth broker: use MOSQUITTO_HEALTHCHECK_* from .env (must match mos_passwd; needs $SYS read in ACLs if you use acl_file).
    healthcheck:
#          'mosquitto_sub -h localhost -p 1883 -u "$$MOSQUITTO_HEALTHCHECK_USERNAME" -P "$$MOSQUITTO_HEALTHCHECK_PASSWORD" -t "$$SYS/broker/uptime" -C 1 -W 5 || exit 1',
      test:
        [
          "CMD-SHELL",
          'mosquitto_sub -h localhost -p 1883 -u "${MOSQUITTO_HEALTHCHECK_USERNAME}" -P "${MOSQUITTO_HEALTHCHECK_PASSWORD}" -t "$$SYS/broker/uptime" -C 1 -W 5 || exit 1',
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
    networks:
      - mqtt
networks:
  mqtt:
    name: mosquitto-net
