services:
  ollama:
    image: ollama/ollama:${IMAGE_VERSION:-latest}
    container_name: ollama
    restart: unless-stopped
    volumes:
      - ../../lib/ollama:/root/.ollama
    ports:
      - 11434:11434
    networks:
      - llama
    env_file:
      - .env
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: "${GPU_COUNT}"
              capabilities: [gpu]
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
networks:
  llama:
    name: llama-net
