services:
  openwakeword:
    image: rhasspy/wyoming-openwakeword:${IMAGE_VERSION:-latest}
    container_name: openwakeword
    hostname: openwakeword
    restart: unless-stopped
    command: --preload-model 'ok_nabu' --custom-model-dir /models
#    ports:
#      - 10400:10400
    volumes:
      - ../../lib/openwakeword:/models
    env_file:
      - .env
    networks:
      - hass
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
networks:
  hass:
    name: hass-net
    external: true
