# usage:
#     docker compose up postfix -d
#     docker compose exec postfix mailq
services:
  postfix:
    image: boky/postfix:${IMAGE_VERSION:-latest}
    hostname: mail-relay
    container_name: postfix
    restart: unless-stopped
    ports:
      - 25:25
      - 587:587
    networks:
      - mail
    volumes:
      - ../../lib/postfix/spool:/var/spool/postfix:rw
      - ../../lib/postfix/sasldb2:/etc/sasldb2
#      - ../../lib/postfix/sasl:/etc/sasl2
    env_file:
      - .env
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "timeout 2 bash -c '</dev/tcp/127.0.0.1/587' || exit 1",
        ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s

networks:
  mail:
    name: postfix-net
