services:
  postgresql:
#    image: postgres:${IMAGE_VERSION:-16}
    image: pgautoupgrade/pgautoupgrade:18-alpine
    hostname: postgresql
    container_name: postgresql
    restart: unless-stopped
    command: >
      postgres
        -c max_wal_size=2GB
        -c checkpoint_completion_target=0.9
    networks:
      - db
    volumes:
      - ../../lib/postgresql:/var/lib/postgresql
      - ../../log/postgresql:/var/log/postgresql/
    shm_size: 128mb
    env_file:
      - .env

networks:
  db:
    name: postgres-net
