services:
  upsd:
    image: gpdm/nut-upsd
    container_name: upsd
    hostname: upsd
    restart: unless-stopped
    privileged: true
    devices:
      - "${UPS_DEVICE}:/dev/ups0:rw"
    volumes:
      - ./config:/etc/nut
    ports:
      - 3493:3493
    env_file:
      - .env
