services:
  backrest:
    image: garethgeorge/backrest:${IMAGE_VERSION:-latest}
    container_name: backrest
    hostname: backrest
    volumes:
      - ./config:/config
      - ../../lib/backrest:/data
      - ${BACKREST_CACHE_PATH}:/cache
      - ${BACKREST_REPOS_PATH}:/repos
      - ${BACKREST_USERDATA_PATH:-/opt}:/userdata
      - ${BACKREST_USERETC_PATH:-/etc}:/useretc
      - ${BACKREST_USERHOME_PATH:-/home}:/userhome
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -fSs http://127.0.0.1:9898/ >/dev/null || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - proxy
#    ports:
#      - 9898:9898
networks:
  proxy:
    external: true
    name: nginx-proxy-net
volumes:
  backups:
    driver: local
    driver_opts:
      type: nfs
      o: nfsvers=4,addr=nas.cats,rw
      device: ":/backups/ummon/restic"
