services:
  redis:
    image: redis:${REDIS_IMAGE_VERSION:-7}
    restart: unless-stopped
    hostname: redis
    networks:
      - redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    image: ghcr.io/romkey/pdxhackerspace-gunky:${IMAGE_VERSION:-latest}
    restart: unless-stopped
    command: ["./bin/rails", "server", "-b", "0.0.0.0"]
    hostname: gunky
    container_name: gunky

#    ports:
#      - "${PORT:-80}:80"
    depends_on:
      - redis
    env_file:
      - .env
    volumes:
      - ../../lib/gunky:/rails/storage
    networks:
      - redis
      - proxy
      - db
#      - cups
    healthcheck:
      test: ["CMD-SHELL", "curl -fSs http://127.0.0.1:3000/ >/dev/null || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  sidekiq:
    image: ghcr.io/romkey/pdxhackerspace-gunky:${IMAGE_VERSION:-latest}
    command: bundle exec sidekiq
    restart: unless-stopped
    depends_on:
      - redis
    env_file:
      - .env
    volumes:
      - ../../lib/gunky:/rails/storage
    networks:
      - redis
      - proxy
      - db
#      - cups
    healthcheck:
      test: ["CMD-SHELL", "pgrep -f sidekiq >/dev/null || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s

networks:
  redis:
    name: gunky-redis-net
  proxy:
    name: nginx-proxy-net
    external: true
  db:
    name: postgres-net
    external: true
  cups:
    name: cups-net
    external: true
