services:
  wiki:
    image: ghcr.io/requarks/wiki:${IMAGE_VERSION:-latest}
    container_name: wiki
    hostname: wiki
    restart: unless-stopped
    networks:
      proxy: null
      db: null
    volumes:
      - ./config.yml:/wiki/config.yml
      - ../../lib/wikijs:/wiki/data
#    ports:
#      - "3001:3001"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

networks:
  proxy:
    external: true
    name: nginx-proxy-net
  db:
    external: true
    name: postgres-net
