#!/usr/bin/env ruby
# frozen_string_literal: true

require "json"
require "fileutils"
require "net/http"
require "securerandom"
require "uri"

ACTIONS = ["sync", "users", "ping", "web-ping", "backup"].freeze

def usage
  $stderr.puts "Usage: ACCESS_TOKEN=USER:PASSWORD #{$PROGRAM_NAME} <action> [args]"
  $stderr.puts "       #{$PROGRAM_NAME} actions"
  exit 1
end

def actions_list
  ACTIONS.join("\n")
end

def require_access_token(action)
  token = ENV["ACCESS_TOKEN"]
  return token unless ["sync", "web-ping", "backup"].include?(action) && (token.nil? || token.strip.empty?)

  $stderr.puts "ACCESS_TOKEN is required"
  exit 1
end

def access_token_parts(token)
  username, password = token.split(":", 2)
  if username.nil? || username.empty? || password.nil? || password.empty?
    $stderr.puts "ACCESS_TOKEN must be in USER:PASSWORD format"
    exit 1
  end
  [username, password]
end

def read_users_json
  input = $stdin.read
  if input.nil? || input.strip.empty?
    $stderr.puts "STDIN must contain a JSON array of users"
    exit 1
  end

  begin
    users = JSON.parse(input)
  rescue JSON::ParserError => e
    $stderr.puts "Invalid JSON input: #{e.message}"
    exit 1
  end

  unless users.is_a?(Array)
    $stderr.puts "Expected JSON array of user records"
    exit 1
  end

  users
end

def build_payload(users)
  lines = []
  lines << "0000145312:37 Override key"
  lines << "# This file is automatically generated"
  override_key = ENV["OVERRIDE_KEY"]
  lines << override_key if override_key && !override_key.strip.empty?

  users.each do |user|
    permissions = user["permissions"] || []
    next unless permissions.include?("Laser")

    rfids = user["rfids"] || []
    next if rfids.empty?

    facility, uid = rfids[0].split(",", 2)
    next if facility.nil? || uid.nil?

    bits = (1 << 25) | (facility.to_i << 17) | (uid.to_i << 1)
    bit_string = format("%026b", bits)

    left_parity = 1
    right_parity = 1
    12.times do |index|
      left_parity ^= bit_string[index + 1].to_i
      right_parity ^= bit_string[index + 13].to_i
    end

    bit_string[0] = "0" if left_parity == 1
    bit_string[25] = "1" if right_parity == 1

    line = format("%07x:26 %s", bit_string.to_i(2), user["name"])
    lines << line
  end

  lines.join("\n") + "\n"
end

def action_users
  users = read_users_json
  payload = build_payload(users)
  $stdout.write(payload)
  exit 0
end

def action_ping(host)
  success = system("ping", "-c", "1", "-W", "5", host)
  exit(success ? 0 : 1)
end

def action_web_ping(host, token)
  username, password = access_token_parts(token)
  uri = URI.parse("http://#{host}/")
  request = Net::HTTP::Get.new(uri.request_uri)
  request.basic_auth(username, password)
  response = Net::HTTP.start(uri.hostname, uri.port) do |http|
    http.request(request)
  end
  unless response.is_a?(Net::HTTPSuccess)
    $stderr.puts "Web ping failed: #{response.code} #{response.body}"
    exit 1
  end
  puts "Web ping ok for #{host}"
  exit 0
end

def action_sync(host, token)
  users = read_users_json
  payload = build_payload(users)
  username, password = access_token_parts(token)

  uri = URI.parse("http://#{host}/edit")
  boundary = "----RubyFormBoundary#{SecureRandom.hex(12)}"

  body = +""
  body << "--#{boundary}\r\n"
  body << "Content-Disposition: form-data; name=\"f\"; filename=\"/auth.txt\"\r\n"
  body << "Content-Type: text/plain\r\n"
  body << "\r\n"
  body << payload
  body << "\r\n"
  body << "--#{boundary}--\r\n"

  request = Net::HTTP::Post.new(uri)
  request.basic_auth(username, password)
  request["Content-Type"] = "multipart/form-data; boundary=#{boundary}"
  request.body = body

  response = Net::HTTP.start(uri.hostname, uri.port) do |http|
    http.request(request)
  end

  unless response.is_a?(Net::HTTPSuccess)
    $stderr.puts "HTTP upload failed: #{response.code} #{response.body}"
    exit 1
  end

  member_name = ENV["MM_USER_NAME"]
  if member_name.nil? || member_name.strip.empty?
    $stderr.puts "MM_USER__NAME is required for sync logging"
    exit 1
  end

  syslog_message("#{member_name} syncing access list")

  puts "Synced laser cutter users for #{host}"
end

def syslog_message(message)
  syslog_server = ENV["SYSLOG_SERVER"]
  syslog_port = ENV["SYSLOG_PORT"]
  if syslog_server.nil? || syslog_server.strip.empty? || syslog_port.nil? || syslog_port.strip.empty?
    $stderr.puts "SYSLOG_SERVER and SYSLOG_PORT are required for syslog logging"
    exit 1
  end

  logged = system("logger", "-n", syslog_server, "-P", syslog_port, "-t", "accesscontrol", message)
  unless logged
    $stderr.puts "Failed to write syslog message"
    exit 1
  end
end

def action_backup(host, name, token)
  backup_root = "/access-backups"
  unless Dir.exist?(backup_root)
    $stderr.puts "#{backup_root} does not exist"
    exit 1
  end

  timestamp = Time.now.strftime("%Y%m%d%H%M%S")
  backup_dir = File.join(backup_root, "#{name}-#{timestamp}")
  FileUtils.mkdir_p(backup_dir)

  username, password = access_token_parts(token)
  paths = ["/config.json", "/log.txt", "/auth.txt"]
  paths.each do |path|
    uri = URI.parse("http://#{host}#{path}")
    request = Net::HTTP::Get.new(uri.request_uri)
    request.basic_auth(username, password)
    response = Net::HTTP.start(uri.hostname, uri.port) do |http|
      http.request(request)
    end
    unless response.is_a?(Net::HTTPSuccess)
      $stderr.puts "Backup failed for #{path}: #{response.code} #{response.body}"
      exit 1
    end

    filename = File.basename(path)
    File.write(File.join(backup_dir, filename), response.body)
  end

  puts "Backed up files to #{backup_dir}"
end

action = ARGV.shift
usage unless action && !action.strip.empty?
unless action == "actions" || ACTIONS.include?(action)
  $stderr.puts "Unknown action: #{action}"
  usage
end

if action == "actions"
  puts actions_list
  exit 0
end

host_required = ["sync", "ping", "web-ping", "backup"].include?(action)
host = ARGV.shift if host_required
usage if host_required && (host.nil? || host.strip.empty?)

access_token = require_access_token(action)

case action
when "users"
  action_users
when "ping"
  action_ping(host)
when "web-ping"
  action_web_ping(host, access_token)
when "backup"
  name = ENV["ACCESS_CONTROLLER_NICKNAME"]
  if name.nil? || name.strip.empty?
    $stderr.puts "ACCESS_CONTROLLER_NICKNAME is required"
    exit 1
  end
  action_backup(host, name, access_token)
when "sync"
  action_sync(host, access_token)
end
