services:
  telegraf:
    image: telegraf:${IMAGE_VERSION:-latest}
    container_name: telegraf
    hostname: telegraf
    restart: unless-stopped
    volumes:
      - ./config/telegraf.conf:/etc/telegraf/telegraf.conf
      - /:/hostfs
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
    networks:
      - influxdb
      - db
      - mariadb
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
networks:
  influxdb:
    name: influxdb-net
    external: true
  db:
    name: postgres-net
    external: true
  mariadb:
    name: mariadb-net
    external: true
