services:
  trimetd:
    image: ghcr.io/romkey/pdxhackstack-trimetd:${IMAGE_VERSION:-latest}
    container_name: trimetd
    hostname: trimetd
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - mqtt
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

networks:
  mqtt:
    name: mosquitto-net
    external: true
